### ISSUE TITLE
Error on t values

### ISSUE THREAD

**Issue by dhalpern** [pennmem/SpinningBrainPlots#1]
This line in the last cell of [GenerateBrainData.ipynb](https://github.com/pennmem/SpinningBrainPlots/blob/main/GenerateBrainData.ipynb)
`t_values = df_e[region_type].astype('category').cat.codes.apply(lambda x: (x+1)/len(values.unique())) # Region based t_values
`

returns an error 
`NameError: name 'values' is not defined`

A bit unclear to me what this line is supposed to be doing so not sure how to fix it exactly

**Comment by bruskajp** [comment]
Fixed by commit 538e286
